### ISSUE TITLE
Downloading the project results in an error

### ISSUE THREAD

**Issue by susanmonnelly** [Lullabot/gatsby-theme-adr#24]
**Describe the bug**
Downloading the project using the suggested command resulted in an error:

`! could not find commit hash for master`

**To Reproduce**
`npx degit github:e0ipso/adr-website-example adr`

The local version of git is 2.32

**Expected behavior**
No error

**Additional context**
The workaround is to specifically point to the main branch in the degit command:
`npx degit github:e0ipso/adr-website-example#main .`

The degit documentation states that master is the default branch.

**Comment by e0ipso** [comment]
According to this commit https://github.com/Rich-Harris/degit/commit/02d3d56d273bf8a5ce7e2bc59c1de17f54976bcc it should have worked. Nonetheless I will update the docs.

Thanks!

**Comment by e0ipso** [comment]
https://github.com/Lullabot/gatsby-theme-adr/commit/cfeb507b48173e8b84659ede81a9c5f8ef44dfb3 fixed this.

Thanks again for your contribution :heart:
