### ISSUE TITLE
Document how to develop against this project

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/gatsby-theme-adr#34]
**Is your feature request related to a problem? Please describe.**

I'm trying to do some work on the ADR theme, but I'm stuck with linking. In the theme itself, gatsby develop says "If you are trying to run a theme directly, use the theme in an example site or starter instead and run that site to test.". In our architecture repo, I ran `npm link @lullabot/gatsby-theme-adr` and the symlink is correct, but I get this plugin error even though I also added it as a dev dependency to our architecture repo:

```
Couldn't find the "gatsby-plugin-image" plugin declared in "/Users/andrew/workspace/lullabot/gatsby-theme-adr/gatsby-config.js".
Tried looking for an installed package in the following paths:
 - /Users/andrew/workspace/lullabot/architecture/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/architecture/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/architecture/node_modules/gatsby/dist/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/architecture/node_modules/gatsby/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/architecture/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/node_modules/gatsby-plugin-image
 - /Users/andrew/node_modules/gatsby-plugin-image
 - /Users/node_modules/gatsby-plugin-image
 - /node_modules/gatsby-plugin-image
```

The [Gatsby Docs](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/building-themes/) promote using Yarn Workspaces, though they also say npm link should work. As well, this repository doesn't mirror the directory structure there, so I'm not sure how to get this going.

**Describe the solution you'd like**

Documentation added to the README, even if it's just links to upstream docs I've missed.

**Comment by e0ipso** [comment]
@deviantintegral did you execute the [step to get the boilerplate code](https://github.com/Lullabot/gatsby-theme-adr#-add-an-adr-website-to-your-software-project=)?

```
# Download the boilerplate project so we can tweak it.
npx degit github:e0ipso/adr-website-example#main docs

# ...
```

That should create an actual theme, that uses this project.

**Comment by deviantintegral** [comment]
I just gave that a try, running:

- degit, followed by npm install
- `cd <path to gatsby-theme-adr clone> && npm link`
- `cd - && npm link @lulllabot/gatsby-theme-adr`
- `npm run-script develop`

Which gave me:

```
npm run-script develop

> my-company-architecture@1.0.0 develop
> gatsby develop

success compile gatsby files - 0.510s

 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-image" plugin declared in "/Users/andrew/workspace/lullabot/gatsby-theme-adr/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /Users/andrew/workspace/lullabot/docs/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/docs/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/docs/node_modules/gatsby/dist/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/docs/node_modules/gatsby/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/docs/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/lullabot/node_modules/gatsby-plugin-image
 - /Users/andrew/workspace/node_modules/gatsby-plugin-image
 - /Users/andrew/node_modules/gatsby-plugin-image
 - /Users/node_modules/gatsby-plugin-image
 - /node_modules/gatsby-plugin-image

not finished load gatsby config - 0.035s
```

**Comment by e0ipso** [comment]
> You switched to a yarn command - should I be using it instead?

No, sorry. I am using `yarn` at my client project and force of habit kicked in.

**Comment by e0ipso** [comment]
It seems this is a non-solvable issue. From what I see we **need** to use yarn workspaces. _sigh_

https://github.com/gatsbyjs/gatsby/issues/25619

**Comment by e0ipso** [comment]
@deviantintegral I have revamped the whole project for this. Then I added some docs.
